# Intro to Recommender Systems Lab

Complete the exercises below to solidify your knowledge and understanding of recommender systems.

For this lab, we are going to be putting together a user similarity based recommender system in a step-by-step fashion. Our data set contains customer grocery purchases, and we will use similar purchase behavior to inform our recommender system. Our recommender system will generate 5 recommendations for each customer based on the purchases they have made.

In [1]:
import pandas as pd
from scipy.spatial.distance import pdist, squareform

In [2]:
data = pd.read_csv('../data/customer_product_sales.csv')

In [3]:
data.head()

,CustomerID,FirstName,LastName,SalesID,ProductID,ProductName,Quantity
0,61288,Rosa,Andersen,134196,229,Bread - Hot Dog Buns,16
1,77352,Myron,Murray,6167892,229,Bread - Hot Dog Buns,20
2,40094,Susan,Stevenson,5970885,229,Bread - Hot Dog Buns,11
3,23548,Tricia,Vincent,6426954,229,Bread - Hot Dog Buns,6
4,78981,Scott,Burch,819094,229,Bread - Hot Dog Buns,20

## Step 1: Create a data frame that contains the total quantity of each product purchased by each customer.

You will need to group by CustomerID and ProductName and then sum the Quantity field.

In [4]:
df = data[['CustomerID','ProductName','Quantity']]

df_quantity = df.groupby(['CustomerID','ProductName']).sum()

df_quantity.head()

                                          Quantity
CustomerID ProductName
33         Apricots - Dried                      1
           Assorted Desserts                     1
           Bandage - Flexible Neon               1
           Bar Mix - Pina Colada, 355 Ml         1
           Beans - Kidney, Canned                1

## Step 2: Use the `pivot_table` method to create a product by customer matrix.

The rows of the matrix should represent the products, the columns should represent the customers, and the values should be the quantities of each product purchased by each customer. You will also need to replace nulls with zeros, which you can do using the `fillna` method.

In [5]:
customer_matrix = pd.pivot_table(df_quantity, index='ProductName', columns='CustomerID', values='Quantity', fill_value=0)
customer_matrix.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0,0,0,0,0,0,0,1,0,0,...,0,25,0,0,0,0,0,0,0,0
"Appetizer - Mini Egg Roll, Shrimp",0,0,0,0,0,0,0,0,0,0,...,25,25,0,0,0,0,0,0,0,0
Appetizer - Mushroom Tart,0,0,0,0,0,0,0,1,0,0,...,25,0,0,0,0,0,0,0,25,0
Appetizer - Sausage Rolls,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,25,25,25,0,25,0
Apricots - Dried,1,0,0,0,1,0,0,0,0,0,...,0,25,0,0,0,0,0,0,0,0

## Step 3: Create a customer similarity matrix using `squareform` and `pdist`. For the distance metric, choose "euclidean."

In [6]:
distances = pd.DataFrame(1/(1+squareform(pdist
        
        (customer_matrix.T,'euclidean'))),
                    
index=customer_matrix.columns, columns=customer_matrix.columns)

                       
distances.head()

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,1.000000,0.077421,0.087047,0.081800,0.080634,0.082709,0.074573,0.083020,0.081503,0.080070,...,0.004811,0.004669,0.004412,0.005019,0.004312,0.004515,0.004583,0.004355,0.004167,0.004333
200,0.077421,1.000000,0.078448,0.076435,0.073693,0.075255,0.075956,0.076435,0.077674,0.076923,...,0.004824,0.004681,0.004431,0.005047,0.004311,0.004521,0.004614,0.004367,0.004166,0.004335
264,0.087047,0.078448,1.000000,0.080070,0.081800,0.080350,0.076923,0.080634,0.082100,0.078448,...,0.004822,0.004674,0.004416,0.005035,0.004322,0.004543,0.004595,0.004365,0.004179,0.004333
356,0.081800,0.076435,0.080070,1.000000,0.076435,0.078187,0.075025,0.082403,0.077171,0.075956,...,0.004816,0.004671,0.004416,0.005038,0.004310,0.004526,0.004578,0.004365,0.004175,0.004339
412,0.080634,0.073693,0.081800,0.076435,1.000000,0.078711,0.075025,0.082403,0.078187,0.078448,...,0.004810,0.004702,0.004414,0.005034,0.004318,0.004530,0.004578,0.004367,0.004177,0.004349

## Step 4: Check your results by generating a list of the top 5 most similar customers for a specific CustomerID.

In [15]:
similars = distances[33].sort_values(ascending=False)[:6]
similarities = similars.index.tolist()
similarities

[33, 264, 3535, 3317, 2503, 3305]

## Step 5: From the data frame you created in Step 1, select the records for the list of similar CustomerIDs you obtained in Step 4.

In [19]:

df_reset = df_quantity.reset_index()

df_reset = df_reset[df_reset['CustomerID'].isin(similarities)]

## Step 6: Aggregate those customer purchase records by ProductName, sum the Quantity field, and then rank them in descending order by quantity.

This will give you the total number of each product purchased by the 5 most similar customers to the customer you selected in order from most purchased to least.

In [20]:
df_agg = df_reset2.groupby(['ProductName','CustomerID']).sum()


df_agg.sort_values(by=['Quantity'],ascending=False)

                                              Quantity
ProductName                       CustomerID
Veal - Inside, Choice             33                 2
Mushrooms - Black, Dried          264                2
Lettuce - Spring Mix              33                 2
Beans - Wax                       3305               2
Pepper - Black, Whole             3317               2
Sardines                          3305               2
Bar - Granola Trail Mix Fruit Nut 2503               2
Chocolate - Dark                  264                2
Salsify, Organic                  33                 2
Knife Plastic - White             2503               2
Butter - Unsalted                 2503               2
Grouper - Fresh                   33                 2
Guinea Fowl                       264                2
Wine - Ej Gallo Sierra Valley     3305               2
Salmon - Sockeye Raw              3305               1
Sauce - Rosee                     3305               1
Remy Red                          264                1
Salsify, Organic                  2503               1
Sage - Ground                     3305               1
Rosemary - Primerba, Paste        3305               1
Raspberries - Fresh               3317               1
Sauce - Demi Glace                33                 1
Raspberries - Fresh               2503               1
Sauce - Gravy, Au Jus, Mix        3317               1
Sauce - Hollandaise               2503               1
Quiche Assorted                   264                1
Rum - Coconut, Malibu             33                 1
Anchovy Paste - 56 G Tube         3535               1
Sauerkraut                        264                1
Sea Bass - Whole                  3535               1
...                                                ...
Cup - Translucent 7 Oz Clear      3305               1
Extract - Lemon                   2503               1
Cup - 6oz, Foam                   3305               1
Cumin - Whole                     264                1
Crush - Cream Soda                3317               1
Creme De Banane - Marie           264                1
Cream Of Tartar                   2503               1
Crackers - Trio                   264                1
Crab - Imitation Flakes           3317               1
Eggplant - Asian                  3535               1
Ezy Change Mophandle              3317               1
Hersey Shakes                     2503               1
Garbage Bags - Clear              3317               1
Hersey Shakes                     33                 1
Halibut - Steaks                  3535               1
Grouper - Fresh                   264                1
Grapes - Red                      33                 1
General Purpose Trigger           33                 1
Garlic - Elephant                 3535               1
Garbage Bags - Clear              3535               1
Fuji Apples                       3305               1
Fenngreek Seed                    3317               1
French Pastry - Mini Chocolate    33                 1
Fondant - Icing                   3535               1
                                  33                 1
Fond - Neutral                    2503               1
Foam Dinner Plate                 3535               1
Flour - Teff                      264                1
Fish - Scallops, Cold Smoked      3535               1
Yogurt - French Vanilla           3305               1

[329 rows x 1 columns]

## Step 7: Filter the list for products that the chosen customer has not yet purchased and then recommend the top 5 products with the highest quantities that are left.

- Merge the ranked products data frame with the customer product matrix on the ProductName field.
- Filter for records where the chosen customer has not purchased the product.
- Show the top 5 results.

In [21]:
recommendations = df_agg.merge(customer_matrix, left_on= ,right_on=  )

KeyError: 'CustomerID'

## Step 8: Now that we have generated product recommendations for a single user, put the pieces together and iterate over a list of all CustomerIDs.

- Create an empty dictionary that will hold the recommendations for all customers.
- Create a list of unique CustomerIDs to iterate over.
- Iterate over the customer list performing steps 4 through 7 for each and appending the results of each iteration to the dictionary you created.

##  Step 9: Store the results in a Pandas data frame. The data frame should a column for Customer ID and then a column for each of the 5 product recommendations for each customer.

## Step 10: Change the distance metric used in Step 3 to something other than euclidean (correlation, cityblock, consine, jaccard, etc.). Regenerate the recommendations for all customers and note the differences.